#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
"""Measure wall-clock time and peak memory for the OCaml and Crane back ends
across a representative size ladder, and emit BENCHMARKS.md + benchmarks.csv.

For each grammar (JSON, CSV, XML) this picks a *representative subset* of the
staged corpus -- roughly one rung per size decade plus the largest rung -- and
runs both back ends on it under ``/usr/bin/time -l`` (macOS), recording:

  * wall-clock seconds (``real``),
  * peak resident set size (``maximum resident set size``, bytes),
  * the parse outcome (``parse_result`` / ``parse_nodes`` / ``num_tokens``), or
    ``overflow`` when the OCaml runner hits ``Stack overflow`` (it parses via
    deep non-tail recursion and cannot handle the large rungs -- see README).

Runs are single-shot and cold (no warmup); the point is the OCaml-vs-Crane
scaling contrast and the large-input showcase, not micro-benchmark precision.
Run after ``make stage-data``; needs both back ends built (``make bench-build``).
"""

import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.environ.get("DATA", os.path.join(HERE, "data"))
BIN = os.path.join(HERE, "_build", "default")
TIME = "/usr/bin/time"
TIMEOUT = 1200                    # s; the 13.5 MB JSON Crane parse is ~534 s
FMTS = ["json", "csv", "xml"]
# Fastest common third-party C++ parser per format (the "reference" column).
REF = {
    "json": ("run_json_ref.exe", "simdjson"),
    "csv": ("run_csv_ref.exe", "csv-parser"),
    "xml": ("run_xml_pugi.exe", "pugixml"),
}


def instances(fmt):
    d = os.path.join(DATA, fmt.upper(), "Instances")
    if not os.path.isdir(d):
        return []
    out = [(os.path.getsize(os.path.join(d, n)), n, os.path.join(d, n))
           for n in os.listdir(d) if not n.startswith(".")]
    out.sort()
    return out


def pick(fmt):
    """~1 file per size decade (nearest staged rung), always including the max.

    Set REPORT_MAX_BYTES to cap the ladder for a quick run (the multi-MB Crane
    parses are slow -- the full 13.5 MB JSON rung alone is ~9 min).
    """
    cap = int(os.environ.get("REPORT_MAX_BYTES", 0)) or None
    files = [f for f in instances(fmt) if cap is None or f[0] <= cap]
    if not files:
        return []
    sizes = [f[0] for f in files]
    lo, hi = sizes[0], sizes[-1]
    targets, t = [], lo
    while t < hi:
        targets.append(t)
        t *= 10
    targets.append(hi)
    picked, seen = [], set()
    for tgt in targets:
        i = min(range(len(files)), key=lambda i: abs(sizes[i] - tgt))
        if i not in seen:
            seen.add(i)
            picked.append(files[i])
    picked.sort()
    return picked


def measure(exe, path):
    """(wall_s, rss_bytes, outcome). outcome: dict | 'overflow' | 'fail' | 'timeout'."""
    if not os.path.exists(exe):
        return None, None, "missing"
    try:
        r = subprocess.run([TIME, "-l", exe, path],
                           capture_output=True, timeout=TIMEOUT)
    except subprocess.TimeoutExpired:
        return None, None, "timeout"
    err = r.stderr.decode("utf-8", "replace")
    out = r.stdout.decode("utf-8", "replace")
    m = re.search(r"([\d.]+)\s+real", err)
    wall = float(m.group(1)) if m else None
    m = re.search(r"(\d+)\s+maximum resident set size", err)
    rss = int(m.group(1)) if m else None
    outcome = "fail"
    try:
        outcome = json.loads(out.strip().splitlines()[-1])
    except Exception:
        if "Stack overflow" in err:
            outcome = "overflow"
    return wall, rss, outcome


def res_str(outcome):
    if isinstance(outcome, dict):
        return outcome.get("parse_result", "?")
    return outcome


def mb(n):
    return "" if n is None else f"{n / 1_000_000:.1f}"


def secs(n):
    return "" if n is None else f"{n:.2f}"


def main():
    rows = []            # csv rows
    md = []
    md.append("# parse-a-lot benchmark report\n")
    md.append("Wall-clock time and peak resident memory for the verified "
              "`Crane.Libraries.ParseALot` pipeline on a representative size "
              "ladder, comparing the two extraction back ends:\n")
    md.append("- **OCaml** — plain Coq→OCaml extraction (`run_<fmt>.exe`).")
    md.append("- **Crane** — Coq→C++ extraction via the Crane plugin "
              "(`run_<fmt>_crane.exe`).")
    md.append("- **reference** — the fastest common third-party C++ parser for "
              "the format (JSON `simdjson`, XML `pugixml`, CSV `csv-parser`); a "
              "hand-written unverified baseline, shown for scale. It reports its "
              "own node count as a work proxy, not ParseALot's parse_nodes.\n")
    md.append("Generated by `report_bench.py` on the `make stage-data` corpus "
              "(single-shot, cold runs; peak RSS via `/usr/bin/time -l`). The "
              "OCaml runner parses by deep non-tail recursion and **stack-"
              "overflows** above a few hundred KB — macOS caps the main-thread "
              "stack below its overflow point, so this is unraisable — while the "
              "Crane C++ runner uses an explicit stack and scales into the "
              "multi-MB range. `overflow` marks where OCaml cannot parse at "
              "all.\n")

    for fmt in FMTS:
        picked = pick(fmt)
        if not picked:
            continue
        ref_exe, ref_lib = REF[fmt]
        md.append(f"## {fmt.upper()} — reference parser: `{ref_lib}`\n")
        md.append(f"| input bytes | OCaml time (s) | OCaml RSS (MB) | OCaml "
                  f"result | Crane time (s) | Crane RSS (MB) | Crane result | "
                  f"{ref_lib} time (s) | {ref_lib} RSS (MB) | {ref_lib} result "
                  f"| parse_nodes | num_tokens | Crane s/MB |")
        md.append("|---:|---:|---:|:--|---:|---:|:--|---:|---:|:--|---:|---:|---:|")
        for size, name, path in picked:
            print(f"  [{fmt}] {name} ({size} B) ...", flush=True)
            ow, orr, oo = measure(os.path.join(BIN, f"run_{fmt}.exe"), path)
            cw, crr, co = measure(os.path.join(BIN, f"run_{fmt}_crane.exe"), path)
            rw, rrr, ro = measure(os.path.join(BIN, ref_exe), path)
            outcome = co if isinstance(co, dict) else (oo if isinstance(oo, dict) else {})
            nodes = outcome.get("parse_nodes", "")
            toks = outcome.get("num_tokens", "")
            spm = f"{cw / (size / 1_000_000):.1f}" if cw else ""
            md.append(f"| {size:,} | {secs(ow)} | {mb(orr)} | {res_str(oo)} "
                      f"| {secs(cw)} | {mb(crr)} | {res_str(co)} "
                      f"| {secs(rw)} | {mb(rrr)} | {res_str(ro)} "
                      f"| {nodes} | {toks} | {spm} |")
            rows.append([fmt, size, name, secs(ow), orr or "", res_str(oo),
                         secs(cw), crr or "", res_str(co),
                         ref_lib, secs(rw), rrr or "", res_str(ro),
                         nodes, toks, spm])
        md.append("")

    md_path = os.path.join(HERE, "BENCHMARKS.md")
    with open(md_path, "w") as f:
        f.write("\n".join(md) + "\n")
    csv_path = os.path.join(HERE, "benchmarks.csv")
    with open(csv_path, "w") as f:
        f.write("format,input_bytes,file,ocaml_time_s,ocaml_rss_bytes,"
                "ocaml_result,crane_time_s,crane_rss_bytes,crane_result,"
                "ref_lib,ref_time_s,ref_rss_bytes,ref_result,"
                "parse_nodes,num_tokens,crane_s_per_mb\n")
        for r in rows:
            f.write(",".join(str(x) for x in r) + "\n")
    print(f"wrote {md_path}\nwrote {csv_path}")


if __name__ == "__main__":
    main()
