// Copyright 2025 Bloomberg Finance L.P.
// Distributed under the terms of the GNU LGPL v2.1 license.

// Test: Reified ITree extraction.
//
// The extracted main function lives inside the struct and there should
// be an auto-generated main() wrapper that calls it via ->run().
//
// with_logging is a CoFixpoint that traverses the tree — its extraction
// is not yet fully supported, so for now we just verify the rest compiles.

#include <itree_reified.h>

#include <iostream>

// The main() wrapper is auto-generated by Crane.
// We just compile and run — if the struct's main() and the wrapper exist, success!
