#include <algorithm>
#include <any>
#include <cassert>
#include <functional>
#include <iostream>
#include <memory>
#include <optional>
#include <ram_empty_wf.h>
#include <stdexcept>
#include <string>
#include <variant>
