// Copyright 2025 Bloomberg Finance L.P.
// Distributed under the terms of the GNU LGPL v2.1 license.

// Regression test: Definition named "main" with erased monad generates
// a valid C++ entry point (no ->run() on plain return type).
//
// The main() wrapper is auto-generated by Crane in the .cpp file.
// This file just needs to compile and link with it.

#include <main_entrypoint.h>
