#include <algorithm>
#include <any>
#include <cassert>
#include <cstdint>
#include <functional>
#include <iostream>
#include <memory>
#include <mini_stm.h>
#include <optional>
#include <stdexcept>
#include <stm_hash_map.h>
#include <string>
#include <utility>
#include <variant>
#include <vector>
