#include <algorithm>
#include <fstream>
#include <functional>
#include <iostream>
#include <memory>
#include <mini_stm.h>
#include <optional>
#include <stm.h>
#include <string>
#include <utility>
#include <variant>
#include <vector>
