#ifndef INCLUDED_GENERATED_METHOD_NAME_CLASH
#define INCLUDED_GENERATED_METHOD_NAME_CLASH

#include <type_traits>
#include <utility>
#include <variant>

struct GeneratedMethodNameClash {
  /// Constructor factory names share the class namespace with helper methods
  /// generated by Crane.  The constructors Clone and V lower to static
  /// factories named clone() and v(), which collide with the generated
  /// clone() const and v() const member functions.  The generated C++ does
  /// not compile because those names cannot be overloaded as static factories
  /// with the same parameter list.
  struct token {
    // TYPES
    struct Clone {};

    struct V {};

    struct Other {
      bool d_a0;
    };

    using variant_t = std::variant<Clone, V, Other>;

  private:
    // DATA
    variant_t d_v_;

  public:
    // CREATORS
    token() {}

    explicit token(Clone _v) : d_v_(_v) {}

    explicit token(V _v) : d_v_(_v) {}

    explicit token(Other _v) : d_v_(std::move(_v)) {}

    token(const token &_other) : d_v_(std::move(_other.clone().d_v_)) {}

    token(token &&_other) : d_v_(std::move(_other.d_v_)) {}

    token &operator=(const token &_other) {
      d_v_ = std::move(_other.clone().d_v_);
      return *this;
    }

    token &operator=(token &&_other) {
      d_v_ = std::move(_other.d_v_);
      return *this;
    }

    // ACCESSORS
    token clone() const {
      if (std::holds_alternative<Clone>(this->v())) {
        return token(Clone{});
      } else if (std::holds_alternative<V>(this->v())) {
        return token(V{});
      } else {
        const auto &[d_a0] = std::get<Other>(this->v());
        return token(Other{d_a0});
      }
    }

    // CREATORS
    static token Clone_() { return token(Clone{}); }

    static token V_() { return token(V{}); }

    static token other(bool a0) { return token(Other{a0}); }

    // MANIPULATORS
    inline variant_t &v_mut() { return d_v_; }

    // ACCESSORS
    const variant_t &v() const { return d_v_; }
  };

  template <typename T1, typename F2>
    requires std::is_invocable_r_v<T1, F2 &, bool &>
  static T1 token_rect(T1 f, T1 f0, F2 &&f1, const token &t) {
    if (std::holds_alternative<typename token::Clone>(t.v())) {
      return f;
    } else if (std::holds_alternative<typename token::V>(t.v())) {
      return f0;
    } else {
      const auto &[d_a0] = std::get<typename token::Other>(t.v());
      return f1(d_a0);
    }
  }

  template <typename T1, typename F2>
    requires std::is_invocable_r_v<T1, F2 &, bool &>
  static T1 token_rec(T1 f, T1 f0, F2 &&f1, const token &t) {
    if (std::holds_alternative<typename token::Clone>(t.v())) {
      return f;
    } else if (std::holds_alternative<typename token::V>(t.v())) {
      return f0;
    } else {
      const auto &[d_a0] = std::get<typename token::Other>(t.v());
      return f1(d_a0);
    }
  }

  static bool is_clone(const token &t);
  static inline const bool sample = is_clone(token::Clone_());
};

#endif // INCLUDED_GENERATED_METHOD_NAME_CLASH
