From Crane Require Import Extraction.
From Crane Require Import Mapping.Std.

Module GeneratedMethodNameClash.

(** Constructor factory names share the class namespace with helper methods
    generated by Crane.  The constructors [Clone] and [V] lower to static
    factories named [clone()] and [v()], which collide with the generated
    [clone() const] and [v() const] member functions.  The generated C++ does
    not compile because those names cannot be overloaded as static factories
    with the same parameter list. *)

Inductive token : Type :=
| Clone : token
| V : token
| Other : bool -> token.

Definition is_clone (t : token) : bool :=
  match t with
  | Clone => true
  | V => false
  | Other b => b
  end.

Definition sample : bool := is_clone Clone.

End GeneratedMethodNameClash.

Crane Extraction "generated_method_name_clash" GeneratedMethodNameClash.
