

(subdir impossible_branch_thunk_call
 (rule
  (targets impossible_branch_thunk_call.t.exe)
  (deps ImpossibleBranchThunkCall.vo impossible_branch_thunk_call.t.cpp (source_tree .))
  (action
   (run %{project_root}/scripts/compile-std.sh %{project_root} impossible_branch_thunk_call.t.exe impossible_branch_thunk_call.cpp impossible_branch_thunk_call.t.cpp)))
 (rule
  (alias runtest)
  (deps impossible_branch_thunk_call.t.exe)
  (action (run ./impossible_branch_thunk_call.t.exe))))
