// Copyright 2025 Bloomberg Finance L.P.
// Distributed under the terms of the GNU LGPL v2.1 license.

// Regression test: top-level main (outside any module) must be renamed
// to _main so it doesn't collide with the auto-generated int main().
//
// The main() wrapper is auto-generated by Crane in the .cpp file.
// This file just needs to compile and link with it.

#include <main_toplevel.h>
